### ISSUE TITLE
CASA table browser not opening MSs

### ISSUE THREAD

**Issue by AlexKurek** [aroffringa/dysco#29]
Im not able to open any MS like suggested in Coockbook. After e.g.:
`browsetable(tablename='P311+61_NGC6946.dysco.sub.shift.avg.weights.ms.archive0.calibrated')`
Im getting:
Could not open table 

> /storage/akurek/extractPy/NGC6946_niter60k_08deg_20asec/P311+61_NGC6946.dysco.sub.shift.avg.weights.ms.archive0.calibrated!

In CASAs table browser window. Dysco is installed, but could it still be because of some problems related to Dysco?

**Comment by aroffringa** [comment]
You'll need the most recent version of Casa for this to work (that depends on the latest casacore version). Dysco is now part of Casacore, so you shouldn't have to install it separately. Moreover, a separate Dysco installation is hard to get working with Casa, because Casa (often) uses a different casacore version then Dysco, which makes it give errors like the one you get. I'll close the issue here. If you keep getting errors in Casa (with the newest version that includes Dysco), it might be best to open a ticket there, as then there's something wrong in how Casa builds Casacore.
