### ISSUE TITLE
DyscoStMan is not registered

### ISSUE THREAD

**Issue by mknapp55** [aroffringa/dysco#7]
I get the following error when trying to access an MS via pyrap.tables:

`RuntimeError: Table DataManager error: Data Manager class DyscoStMan is not registered
  Check (DY)LD_LIBRARY_PATH matches the libraries used during the build of DyscoStMan`

I've installed most of the relevant packages via Kern and updated them to the most recent release.  I also tried installing Dysco from source.  I manually added the dysco library to my path.  Is this an issue of the order in which various tools need to be installed?

**Comment by aroffringa** [comment]
I'm not sure, it could be multiple things. The error means that Casacore didn't find the dysco library, or couldn't load it. Kern comes with Dysco preinstalled, so you shouldn't have to install it. 

Indeed it can be a path problem, but if you say you've checked that, something else is wrong. One thing that's important, is that dysco is compiled with the same casacore libraries as python-casacore (which is what pyrap is now called), but that seems unlikely to be the issue here. Maybe best to ask the Kern maintainer, maybe it has to do with python-casacore not using the normal search paths.

**Comment by mknapp55** [comment]
Would you suggest uninstalling casacore and dysco and just reinstalling casacore (via Kern)?  What about pyrap?  

I'm fairly confident I fixed the path problem because I was getting errors about not being able to find specific libraries but those are gone now and only the error above remains.

**Comment by aroffringa** [comment]
I think best would be to use everything from Kern, and don't compile stuff yourself. Then, if things don't work, you can report it as a bug of Kern.
